#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync, cpSync, readdirSync } from "node:fs";
import { resolve, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const clappsDir = resolve(root, "clapps");

/**
 * Build-time sync:
 * - clapps/<id>/components/*.tsx -> packages/web-app/src/components/primitives/*.tsx
 * - clapps/<id>/handlers/*.ts -> packages/connect/src/*.ts
 *
 * Also generates:
 * - packages/web-app/src/components/primitives/index.ts  (barrel exports)
 * - packages/web-app/src/components/_component-map.ts     (componentMap for LayoutNodeRenderer)
 *
 * This keeps each clapp as the source-of-truth while preserving current package build layout.
 */
const TARGETS = {
  components: resolve(root, "packages", "web-app", "src", "components", "primitives"),
  handlers: resolve(root, "packages", "connect", "src"),
};

// Core primitives — framework-level components that live in the main repo
const CORE_COMPONENTS = [
  "Card", "Column", "Row", "Heading", "TextInput", "IntentForm",
  "IntentButton", "Skeleton", "List", "ListItem", "Conditional",
  "MarkdownContent", "Icon",
];
const CORE_UTILITIES = [
  { file: "FormContext", exports: ["FormProvider", "useFormContext"] },
];

function loadJson(path) {
  return JSON.parse(readFileSync(path, "utf-8"));
}

function copyRelative(clappRoot, relativePath, targetDir) {
  const src = resolve(clappRoot, relativePath);
  if (!existsSync(src)) {
    console.warn(`⚠️  Missing source: ${src}`);
    return;
  }
  mkdirSync(targetDir, { recursive: true });
  const dest = resolve(targetDir, basename(relativePath));
  cpSync(src, dest);
  console.log(`sync ${relativePath} -> ${dest.replace(root + "/", "")}`);
}

/** Extract component name from a relative path like "components/AccountCard.tsx" */
function componentName(relPath) {
  return basename(relPath, ".tsx");
}

function generateBarrelFile(clappComponents) {
  const lines = ["// AUTO-GENERATED by sync-clapps.mjs — DO NOT EDIT"];

  // Core primitives
  lines.push("// Core primitives");
  for (const name of CORE_COMPONENTS) {
    lines.push(`export { ${name} } from "./${name}";`);
  }
  for (const util of CORE_UTILITIES) {
    lines.push(`export { ${util.exports.join(", ")} } from "./${util.file}";`);
  }

  // Clapp components grouped by clapp name
  for (const { clappName, components } of clappComponents) {
    lines.push("");
    lines.push(`// ${clappName}`);
    for (const name of components) {
      lines.push(`export { ${name} } from "./${name}";`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function generateComponentMap(clappComponents) {
  const lines = ["// AUTO-GENERATED by sync-clapps.mjs — DO NOT EDIT"];
  lines.push('import type { ComponentType } from "react";');

  // Collect all component names for the map
  const allComponents = [...CORE_COMPONENTS];
  const allImports = [];

  // Core imports
  for (const name of CORE_COMPONENTS) {
    allImports.push(`import { ${name} } from "./primitives/${name}";`);
  }

  // Clapp imports
  for (const { components } of clappComponents) {
    for (const name of components) {
      allImports.push(`import { ${name} } from "./primitives/${name}";`);
      allComponents.push(name);
    }
  }

  lines.push(...allImports);
  lines.push("");
  lines.push("export const componentMap: Record<string, ComponentType<any>> = {");
  lines.push(`  ${allComponents.join(", ")},`);
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function main() {
  if (!existsSync(clappsDir)) {
    console.log("No clapps directory found; skipping sync.");
    return;
  }

  const clappIds = readdirSync(clappsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  // Collect clapp component info for code generation
  const clappComponents = [];

  for (const clappId of clappIds) {
    const clappRoot = resolve(clappsDir, clappId);
    const manifestPath = resolve(clappRoot, "clapp.json");
    if (!existsSync(manifestPath)) continue;

    const manifest = loadJson(manifestPath);
    const components = Array.isArray(manifest.components) ? manifest.components : [];
    const handlers = Array.isArray(manifest.handlers) ? manifest.handlers : [];

    for (const rel of components) copyRelative(clappRoot, rel, TARGETS.components);
    for (const rel of handlers) copyRelative(clappRoot, rel, TARGETS.handlers);

    // Track component names for generation
    if (components.length > 0) {
      clappComponents.push({
        clappName: manifest.name || `@clapps/${clappId}`,
        components: components.map(componentName),
      });
    }
  }

  // Generate barrel file: primitives/index.ts
  const barrelPath = resolve(TARGETS.components, "index.ts");
  writeFileSync(barrelPath, generateBarrelFile(clappComponents), "utf-8");
  console.log(`generate ${barrelPath.replace(root + "/", "")}`);

  // Generate component map: _component-map.ts
  const mapPath = resolve(root, "packages", "web-app", "src", "components", "_component-map.ts");
  writeFileSync(mapPath, generateComponentMap(clappComponents), "utf-8");
  console.log(`generate ${mapPath.replace(root + "/", "")}`);
}

try {
  main();
} catch (err) {
  console.error(err);
  process.exit(1);
}
